name: Neon

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_C_COMPILER: gcc
  CMAKE_CXX_COMPILER: g++
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Google benchmark
      run: git clone https://github.com/google/benchmark; cmake -S benchmark -B benchmark/build -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_TESTING=NO ; cmake --build benchmark/build; cmake --install benchmark/build --prefix ~/.local
    
    - name: Install Exo
      run: git clone https://github.com/exo-lang/exo.git ; cd exo; python3 -m pip install build ; python3 -m build . ; python3 -m pip install dist/*.whl

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --preset apple-silicon

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}} -R correctness
