name: Neon

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CC: clang # This will be system AppleClang
  CXX: clang++ # This will be system AppleClang
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
          
    - name: Install Exo
      run: git clone https://github.com/exo-lang/exo.git ; cd exo; python -m pip install build ; python -m pip uninstall exo-lang; python -m build . ; python -m pip install dist/*.whl

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --preset apple-silicon -DCMAKE_PREFIX_PATH=/Users/yuka/benchmark/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}} -R correctness
